### ISSUE TITLE
Javascript VS C++

### ISSUE THREAD

**Issue by baloyan** [GhadaAlmashaqbeh/CacheCash#56]
Here is a small question which I would like to have your attention.
So, if we would like to keep C++ Client side and at the same time have Javascript version of it, then 
CP and Cache side are going to be different implementation for every case (C++, javascript), because if client is in C++ we just use OpenSSL if it is in Javascript we have to use integrated HTTP(S) server.

1. One idea just come up, which can be stupid, but the idea is to have separate branches or repo for C++ and Javascript implementation of Client.
2. Another one, which I am not sure, but I think it is possible I have to check it out, to have common implementation of CP and Caches.
3. YOUR idea ?

Please let me know your ideas what we can do and what is the best option

**Comment by JustinCappos** [comment]
Can you explain more about why this would look different to a cache?
Doesn't a HTTPS POST request look the same regardless of whether the client
is JS or C++?

**Comment by baloyan** [comment]
for C++ case basically we just read stream based on SSL object using `SSL_read(...)` but if it is JavaScript  we have to use something like this to handle request

```
  HttpServer server;
  server.config.port = 8080;

  // POST request
  server.resource["^/*"]["POST"] = [&](std::shared_ptr<HttpServer::Response> response,
                                       std::shared_ptr<HttpServer::Request> request) {
...
}
```
I think it is possible to separate these to calls based on some flag or something like that.
am I clear ?

**Comment by lukpueh** [comment]
@baloyan, I guess you are talking about the *historical* content provider and cache implementations, where you use a non-standardized protocol on top of TCP/SSL?

I think the ultimate goal is to, independently of the client, make cp and caches HTTPS endpoints. Then you don't need separate cp and cache implementations for different clients, because they will always listen for HTTP(S) requests, as @JustinCappos has pointed out.

**Comment by JustinCappos** [comment]
Thanks for clarifying.  This is what I am suggesting.

**Comment by baloyan** [comment]
So, I had a offline discussion with Lukas. It means I have to change current CacheCash projects's implementation, because it is not HTTP(S) based. This is why I posted this issue.
