### ISSUE TITLE
TODO #2 Implementing HTTP/HTTPS

### ISSUE THREAD

**Issue by baloyan** [GhadaAlmashaqbeh/CacheCash#58]
- Implement HTTP/HTTPS based connection between Clien and CP, Client and Cache and Cache and CP

**Comment by baloyan** [comment]
I start working on it.

**Comment by baloyan** [comment]
Made the first HTTP connection between Cache and CP

**Comment by baloyan** [comment]
Done!

**Comment by JustinCappos** [comment]
Great!
