### ISSUE TITLE
Using RTMP(s)/DASH/HLS? 

### ISSUE THREAD

**Issue by SantiagoTorres** [GhadaAlmashaqbeh/CacheCash#59]
After looking at ticket #56 , I was left wondering whether HTTP is the best choice, at least for the content providers.

 I'm assuming that the content sent will be media, which is usually streamed using [RTMP](https://en.wikipedia.org/wiki/Real-Time_Messaging_Protocol) or other HTTP extended protocols like [HSL](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)/[HTTP-DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP).
If this has been asked somewhere else/already, please disregard.

**Comment by baloyan** [comment]
Actually you are right @SantiagoTorres  it is going to be stream.
So, I would like see here @JustinCappos, @lukpueh and @vladimir-v-diaz  opinions as a comment.

**Comment by JustinCappos** [comment]
Something like DASH is complicated in CacheCash.  You can't decode content
without a collection of blocks from difference sources.  So, really you
need a few MB before you get anything.  As such, I would think traditional
streaming protocols at that level will not work well.

However, I would be happy to be proven wrong if someone else knows things I
do not...

**Comment by SantiagoTorres** [comment]
Right, I didn't consider that. Something to consider is that JS can only keep persistent connections through websockets or [media source extensions](https://en.wikipedia.org/wiki/Media_Source_Extensions), that I don't think would work for a home-brewed streaming protocol. I have a feeling that otherwise the overhead will be dominated by the RTT and/or reshuffling out-of-order datablocks.
